export GIT_NAME="jsmith"
export TIME_ZONE="Europe/Amsterdam"
export MUTT_REALNAME="John Smith"
export MUTT_USERNAME="j.smith"
export MUTT_DOMAIN="@outlook.com"
export MUTT_PASSWORD="Foo"
export MUTT_LANG="nl_NL"
export MUTT_AUTH="login"
