[general]
import = ["~/dotfiles-linux/alacritty/alacritty.toml", "~/dotfiles-windows/alacritty/alacritty.toml"]
live_config_reload = true

[scrolling]
history = 100000

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
chars = "\b"
key = "Back"
mods = "Control"

# Bindings mapped to F13-F24 keys to enable binds that are otherwise not
# possible in a terminal
[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[22;2~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "Space"
mods = "Control"

[colors.primary]
background = '#000000'
foreground = '#c5c9c5'

# https://github.com/alacritty/alacritty-theme/blob/master/themes/kanagawa_dragon.toml
[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'

[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'

red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
