[general]
import = ["~/dotfiles-linux/alacritty/alacritty.toml", "~/dotfiles-windows/alacritty/alacritty.toml"]
live_config_reload = true

[scrolling]
history = 100000

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
chars = "\b"
key = "Back"
mods = "Control"

# Bindings mapped to F13-F24 keys to enable binds that are otherwise not
# possible in a terminal
[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[22;2~"
key = "Tab"
mods = "Control|Shift"

# [[keyboard.bindings]]
# chars = "\u001B[24;2~"
# key = "Space"
# mods = "Control"
