[general]
import = ["~/dotfiles-linux/alacritty/alacritty.toml", "~/dotfiles-windows/alacritty/alacritty.toml"]
live_config_reload = true

[scrolling]
history = 100000
multiplier = 1

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
