import:
  - ~/dotfiles-linux/alacritty/alacritty.yml
  - ~/dotfiles-windows/alacritty/alacritty.yml

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

scrolling:
  history: 10000
  multiplier: 3

live_config_reload: true

key_bindings:
  - { key: Return,    mods: Alt,                        action: ReceiveChar}
  - { key: F11,       mods: Alt,                        action: ToggleFullscreen}
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp   }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop    }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }
  - { key: Tab,       mods: Control,                    chars: "\e[1;5I" }
  - { key: Tab,       mods: Control|Shift,              chars: "\e[1;6I" }
  - { key: Delete,    mods: Control,                    chars: "\e[3;5~" }
  - { key: V,         mods: Control|Alt,                chars: "\e[23;2~"} # send <F23> to enable copy-mode for tmux.
  - { key: Space,     mods: Control,                    chars: "\e[24;2~"} # send <F24> so vim can detect it.
  - { key: Back,      mods: Control,                    chars: "\x08"}
