[tool.ruff]
line-length = 80
target-version = "py312"

[tool.ruff.lint]
select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "I",  # isort
    "N",  # PEP8 naming
    "D",  # pydocstyle
]
