return {
    "tpope/vim-fugitive",
    cmd = {
        "G",
        "GBrowse",
        "GDelete",
        "GMove",
        "GRename",
        "Gclog",
        "Gdiffsplit",
        "Gedit",
        "Ggrep",
        "Git",
        "Glgrep",
        "Gllog",
        "Gread",
        "Gsplit",
        "Gvdiffsplit",
        "Gwrite",
    },
    keys = {
        "<leader>G",
        "<leader>gf",
        "<leader>gp",
        "<leader>gP",
        "<leader>gs",
        "<leader>gu",
        "<leader>gt",
        "<leader>gU",
        "<leader>gT",
        "<leader>gac",
        "<leader>gcc",
        "<leader>ge",
        "<leader>gae",
        "<leader>gce",
        "<leader>gr",
        "<leader>gar",
        "<leader>gcr",
        "<leader>gR",
        "<leader>gd",
        "<leader>gD",
        { "<leader>gm", mode = { "n", "x" } },
        { "<leader>gi", mode = { "n", "x" } },
        "<leader>gM",
        "<leader>gI",
        "<leader>g<CR>",
        "<leader>g<BS>",
    },
    config = function()
        require("config.fugitive")
    end
}
