local mapper = require("helpers.keymapper")

mapper.nnoremap('<leader>G', function()
    vim.cmd('G')
    vim.cmd('wincmd H')
end)
mapper.nnoremap('<leader>gf', '<Cmd>G fetch<CR>')
mapper.nnoremap('<leader>gp', '<Cmd>G pull<CR>')
mapper.nnoremap('<leader>gP', '<Cmd>!git-update<CR>')
mapper.nnoremap('<leader>gs', ':G switch ')
mapper.nnoremap('<leader>gu', '<Cmd>G push<CR>')
mapper.nnoremap('<leader>gt', '<Cmd>G push --tags<CR>')
mapper.nnoremap('<leader>gU', '<Cmd>G push --force-with-lease<CR>')
mapper.nnoremap('<leader>gT', '<Cmd>G push --tags --force-with-lease<CR>')
mapper.nnoremap('<leader>gac', '<Cmd>G cherry-pick --abort<CR>')
mapper.nnoremap('<leader>gcc', '<Cmd>G cherry-pick --continue<CR>')
mapper.nnoremap('<leader>ge', ':G merge ')
mapper.nnoremap('<leader>gae', '<Cmd>G merge --abort<CR>')
mapper.nnoremap('<leader>gce', '<Cmd>G merge --continue<CR>')
mapper.nnoremap('<leader>gr', ':G rebase ')
mapper.nnoremap('<leader>gar', '<Cmd>G rebase --abort<CR>')
mapper.nnoremap('<leader>gcr', '<Cmd>G rebase --continue<CR>')
mapper.nnoremap('<leader>gR', ':G reset ')
mapper.nnoremap('<leader>gd', function()
    vim.cmd('silent! normal gf')
    vim.cmd('wincmd o')
    vim.cmd('Gvdiffsplit')
end)
mapper.nnoremap('<leader>gD', ':Gvdiffsplit ')
mapper.nnoremap('<leader>gy', ':G difftool -y ')
mapper.silent_nnoremap('<leader>gm', '<Cmd>diffget //2<CR>')
mapper.silent_nnoremap('<leader>gi', '<Cmd>diffget //3<CR>')
mapper.silent_nnoremap('<leader>g<CR>', [[/<[<]\+\|==[=]\+\|>[>]\+<CR>]])
mapper.silent_nnoremap('<leader>g<BS>', [[?<[<]\+\|==[=]\+\|>[>]\+<CR>]])
