require('config.treesitter')

require('config.cmp')
require('config.hop')
require('config.linux')
require('config.lsp')
require('config.lualine')
require('config.mason')
require('config.neogen')
require('config.null-ls')
require('config.oil')
require('config.orgmode')
require('config.highlight-yank')
require('config.local-shada')
require('config.global-marks')
