require('config.treesitter')
require('config.treesitter-context')

require('config.cmp')
require('config.hop')
require('config.linux')
require('config.lsp-init')
require('config.lsp-mappings')
require('config.lsp-servers')
require('config.lualine')
require('config.mason')
require('config.neogen')
require('config.null-ls')
require('config.oil')
require('config.orgmode')
require('config.autocmds')
